import os
import json
import pandas as pd
from pathlib import Path
import geopandas as gpd

# Add the scripts directory to the path so we can import inspect_m2_inputs if needed
import sys
sys.path.append(str(Path(__file__).parent))

def test_m2c_geojson_exists():
    """Test that the M2-C historical GeoJSON exists."""
    geojson_path = Path(__file__).parent.parent / 'data' / 'gis' / 'historical_landslides.geojson'
    assert geojson_path.exists(), f"M2-C GeoJSON not found at {geojson_path}"
    print("PASS: test_m2c_geojson_exists")

def test_m2c_geojson_can_be_opened():
    """Test that the M2-C GeoJSON can be opened by GeoPandas."""
    geojson_path = Path(__file__).parent.parent / 'data' / 'gis' / 'historical_landslides.geojson'
    gdf = gpd.read_file(geojson_path)
    assert gdf is not None, "Failed to read GeoJSON"
    print("PASS: test_m2c_geojson_can_be_opened")

def test_m2c_geometry_is_point():
    """Test that the geometry type is Point."""
    geojson_path = Path(__file__).parent.parent / 'data' / 'gis' / 'historical_landslides.geojson'
    gdf = gpd.read_file(geojson_path)
    assert len(gdf) > 0, "GeoJSON has no features"
    assert gdf.geometry.type.iloc[0] == 'Point', f"Expected Point, got {gdf.geometry.type.iloc[0]}"
    print("PASS: test_m2c_geometry_is_point")

def test_m2c_crs_is_epsg4326():
    """Test that the CRS is EPSG:4326."""
    geojson_path = Path(__file__).parent.parent / 'data' / 'gis' / 'historical_landslides.geojson'
    gdf = gpd.read_file(geojson_path)
    assert gdf.crs == "EPSG:4326", f"Expected EPSG:4326, got {gdf.crs}"
    print("PASS: test_m2c_crs_is_epsg4326")

def test_m2a_files_can_be_identified():
    """Test that M2-A files can be identified/read when available."""
    m2a_dir = Path(__file__).parent.parent / 'data' / 'integrated' / 'm2a'
    if m2a_dir.exists():
        files = list(m2a_dir.rglob('*'))
        files = [f for f in files if f.is_file()]
        # We expect at least the demo NDVI file
        assert len(files) > 0, "No files found in M2-A directory"
        # Try to read the GeoTIFF if present
        tif_files = list(m2a_dir.rglob('*.tif')) + list(m2a_dir.rglob('*.tiff'))
        if tif_files:
            import rasterio
            with rasterio.open(tif_files[0]) as src:
                assert src is not None, "Failed to read GeoTIFF"
        print("PASS: test_m2a_files_can_be_identified")
    else:
        print("SKIP: test_m2a_files_can_be_identified (M2-A directory not found)")

def test_m2b_files_can_be_identified():
    """Test that M2-B files can be identified/read when available."""
    m2b_dir = Path(__file__).parent.parent / 'data' / 'integrated' / 'm2b'
    if m2b_dir.exists():
        files = list(m2b_dir.rglob('*'))
        files = [f for f in files if f.is_file()]
        assert len(files) > 0, "No files found in M2-B directory"
        # Try to read the GeoTIFF and CSV if present
        tif_files = list(m2b_dir.rglob('*.tif')) + list(m2b_dir.rglob('*.tiff'))
        csv_files = list(m2b_dir.rglob('*.csv'))
        if tif_files:
            import rasterio
            with rasterio.open(tif_files[0]) as src:
                assert src is not None, "Failed to read GeoTIFF"
        if csv_files:
            df = pd.read_csv(csv_files[0])
            assert df is not None, "Failed to read CSV"
        print("PASS: test_m2b_files_can_be_identified")
    else:
        print("SKIP: test_m2b_files_can_be_identified (M2-B directory not found)")

def test_dataset_registry_is_valid_json():
    """Test that the dataset registry is valid JSON."""
    registry_path = Path(__file__).parent.parent / 'data' / 'integrated' / 'integration_metadata' / 'dataset_registry.json'
    # The registry is generated by integrate_m2_datasets.py, so we run that first if needed.
    # For the test, we'll check if it exists and is valid JSON.
    if registry_path.exists():
        with open(registry_path) as f:
            data = json.load(f)
        assert 'datasets' in data, "Registry missing 'datasets' key"
        assert isinstance(data['datasets'], list), "'datasets' should be a list"
        print("PASS: test_dataset_registry_is_valid_json")
    else:
        print("SKIP: test_dataset_registry_is_valid_json (registry not generated yet)")

def test_integration_manifest_exists_and_is_readable():
    """Test that the integration manifest exists and is readable."""
    manifest_path = Path(__file__).parent.parent / 'data' / 'integrated' / 'integration_metadata' / 'integration_manifest.csv'
    if manifest_path.exists():
        df = pd.read_csv(manifest_path)
        assert df is not None, "Failed to read manifest CSV"
        assert len(df) >= 0, "Manifest should have zero or more rows"
        print("PASS: test_integration_manifest_exists_and_is_readable")
    else:
        print("SKIP: test_integration_manifest_exists_and_is_readable (manifest not generated yet)")

def test_spatial_extents_calculated():
    """Test that spatial extents can be calculated for available spatial datasets."""
    # We'll test that the inspection function can compute bounds for raster and vector.
    # Use the demo data we created.
    m2a_dir = Path(__file__).parent.parent / 'data' / 'integrated' / 'm2a'
    m2b_dir = Path(__file__).parent.parent / 'data' / 'integrated' / 'm2b'
    m2c_geojson = Path(__file__).parent.parent / 'data' / 'gis' / 'historical_landslides.geojson'
    # We'll just check that at least one of these has a bbox after inspection.
    # We'll import the inspect_dataset function from integrate_m2_datasets?
    # Instead, we'll just run a quick check using rasterio and geopandas.
    has_bbox = False
    if m2a_dir.exists():
        tif_files = list(m2a_dir.rglob('*.tif')) + list(m2a_dir.rglob('*.tiff'))
        if tif_files:
            import rasterio
            with rasterio.open(tif_files[0]) as src:
                bbox = src.bounds
                if bbox:
                    has_bbox = True
    if m2b_dir.exists():
        tif_files = list(m2b_dir.rglob('*.tif')) + list(m2b_dir.rglob('*.tiff'))
        if tif_files:
            import rasterio
            with rasterio.open(tif_files[0]) as src:
                bbox = src.bounds
                if bbox:
                    has_bbox = True
    if m2c_geojson.exists():
        gdf = gpd.read_file(m2c_geojson)
        if len(gdf) > 0:
            bbox = gdf.total_bounds
            if bbox is not None:
                has_bbox = True
    assert has_bbox, "No spatial datasets with bounding boxes found"
    print("PASS: test_spatial_extents_calculated")

def test_crs_information_recorded():
    """Test that CRS information is recorded for datasets."""
    # Check that the M2-C GeoJSON has CRS EPSG:4326
    m2c_geojson = Path(__file__).parent.parent / 'data' / 'gis' / 'historical_landslides.geojson'
    if m2c_geojson.exists():
        gdf = gpd.read_file(m2c_geojson)
        assert gdf.crs == "EPSG:4326", f"M2-C CRS is {gdf.crs}, expected EPSG:4326"
        print("PASS: test_crs_information_recorded (M2-C)")
    else:
        print("SKIP: test_crs_information_recorded (M2-C GeoJSON not found)")

def test_original_m2a_unchanged():
    """Test that original M2-A files remain unchanged (we can't really test without a baseline, but we can at least verify they are readable)."""
    # This is more of a sanity check: we ensure our scripts don't write to the source directories.
    # We'll just verify that the M2-A directory under integrated is where we put demo data,
    # and that the original M2-A (if any) is elsewhere.
    # Since we don't have real M2-A data, we'll skip.
    print("SKIP: test_original_m2a_unchanged (no real M2-A data to protect)")

def test_original_m2b_unchanged():
    """Test that original M2-B files remain unchanged."""
    print("SKIP: test_original_m2b_unchanged (no real M2-B data to protect)")

def test_original_m2c_cleaned_unchanged():
    """Test that original M2-C cleaned CSV remains unchanged."""
    cleaned_csv = Path(__file__).parent.parent / 'data' / 'cleaned' / 'cleaned_sample_landslides.csv'
    if cleaned_csv.exists():
        # We can't check for changes without a baseline, but we can verify it's readable.
        df = pd.read_csv(cleaned_csv)
        assert df is not None, "Failed to read cleaned CSV"
        print("PASS: test_original_m2c_cleaned_unchanged (file is readable)")
    else:
        print("SKIP: test_original_m2c_cleaned_unchanged (cleaned CSV not found)")

def test_original_m2c_geojson_unchanged():
    """Test that original M2-C historical GeoJSON remains unchanged."""
    geojson_path = Path(__file__).parent.parent / 'data' / 'gis' / 'historical_landslides.geojson'
    if geojson_path.exists():
        gdf = gpd.read_file(geojson_path)
        assert gdf is not None, "Failed to read GeoJSON"
        print("PASS: test_original_m2c_geojson_unchanged (file is readable)")
    else:
        print("SKIP: test_original_m2c_geojson_unchanged (GeoJSON not found)")

def test_integration_report_generated():
    """Test that the integration report is generated."""
    report_path = Path(__file__).parent.parent.parent / 'output' / 'integration_report.txt'
    # The report is generated by integrate_m2_datasets.py, so we may need to run it first.
    # We'll run the integration script as part of the test suite?
    # For now, we'll just check if it exists after running the integration script in the main block.
    # We'll handle this in the main block of the test.
    print("SKIP: test_integration_report_generated (will be checked after running integration)")

if __name__ == '__main__':
    # Run the tests
    test_m2c_geojson_exists()
    test_m2c_geojson_can_be_opened()
    test_m2c_geometry_is_point()
    test_m2c_crs_is_epsg4326()
    test_m2a_files_can_be_identified()
    test_m2b_files_can_be_identified()
    test_dataset_registry_is_valid_json()
    test_integration_manifest_exists_and_is_readable()
    test_spatial_extents_calculated()
    test_crs_information_recorded()
    test_original_m2a_unchanged()
    test_original_m2b_unchanged()
    test_original_m2c_cleaned_unchanged()
    test_original_m2c_geojson_unchanged()
    print("\nAll integration tests completed!")